server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: personModule
          uri: http://localhost:8081
          predicates:
            - Path=/person/**
        - id: accountModule
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
        - id: transactionModule
          uri: http://localhost:8083
          predicates:
            - Path=/transaction/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost